### ISSUE TITLE
저장소 이름을 정한다. - 5월 19일

### ISSUE THREAD

**Issue by pobiconan** [woowacourse/javable#49]
stack-java: 가볍지만 의미있는 글들의 모음
seed-java -> leaf-java -> branch-java, root-java: 가볍지만 의미있는 글
culture-java: 코딩 문화에 변화를 만드는, 선도하는
cloud-java: 글들의 모음
space-java: 테크코스의 우주 느낌을 살려서
crouse-java: 우테코 크루들의 모음
javable-자바의 성경, kotlinable, swiftable, javascriptable
티끌-java

**Comment by gracefulBrown** [comment]
https://docs.google.com/forms/d/1HJNsSMRibwrmf9CggFP_-TIwMRCUsSgfs7yocR48rjw/edit
