### ISSUE TITLE
[티거] 객체지향 생활 체조

### ISSUE THREAD

**Issue by kimevanjunseok** [woowacourse/javable#70]
일급컬렉션을 정리하면서 객체지향 생활 체조의 9가지의 규칙을 나누어서 정리하는 것은 어떨까 생각합니다.
레벨1때 객체지향 생활 체조가 있다는 말을 듣고 보았지만 일급컬렉션처럼 바로 와닿지 않았습니다.
그래서 태그기능도 생겼으니 규칙을 나누어서 정리하는 것은 어떨까 생각합니다.

**Comment by YerinCho** [comment]
올려드립니다 ☺️

규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.
규칙 2: else 예약어를 쓰지 않는다.
규칙 3: 모든 원시값과 문자열을 포장한다.
규칙 4: 한 줄에 점을 하나만 찍는다.
규칙 5: 줄여쓰지 않는다(축약 금지).
규칙 6: 모든 엔티티를 작게 유지한다.
규칙 7: 2개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
규칙 8: 일급 콜렉션을 쓴다.
규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.
